// Package main (fauxmailer) generates fake emails and sends them via SMTP.
package main // import "github.com/inbucket/fauxmailer"

import (
	"bytes"
	"flag"
	"log"

	"github.com/jhillyerd/enmime"
	"github.com/manveru/faker"
)

var (
	// Flags.
	host    = flag.String("host", "localhost:25", "host:port of SMTP server")
	verbose = flag.Bool("verbose", false, "enable verbose output")
	from    = flag.String("from", "admin@freemailzone.com", "Orign")
	to      = flag.String("to", "www@freemailzone.com", "Destination")
	subject = flag.String("subject", "Free mail zone - how to", "Subject")
/*
	signature = flag.String(
		"signature",
		"Generated by https://github.com/inbucket/fauxmailer",
		"signature")
		*/
)

func main() {
	flag.Parse()

	fake, err := faker.New("en")
	if err != nil {
		log.Fatal(err)
	}

	sender := enmime.NewSMTP(*host, nil)
	buf := &bytes.Buffer{}

	msg := generateMessage(fake)
	if *verbose {
		buf.Reset()
		part, err := msg.Build()
		if err != nil {
			log.Fatal(err)
		}
		err = part.Encode(buf)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Sending:\n%s", buf.String())
	}
	if err := msg.Send(sender); err != nil {
		log.Fatal(err)
	}

}

// generateMessage uses faker to create a random message struct.
func generateMessage(fake *faker.Faker) enmime.MailBuilder {
	// Use provided To address if available.
	//company := fake.CompanyName()

	// Plain text.
	/*
	cosig := fmt.Sprintf("%s <%s>, %s\r\n%s, \"%s\"",
		fake.Name(),
		*from,
		fake.JobTitle(),
		company,
		fake.CompanyCatchPhrase())
		*/
//	paragraphs := fake.Paragraphs(4, true)
	/*
	textp := append(make([]string, 0), paragraphs...)
	textp = append(textp, cosig)
	if *signature != "" {
		textp = append(textp, "--\r\n"+*signature)
	}
*/


	// HTML.
	/*
	cosig = fmt.Sprintf("%s &lt;<a href=\"mailto:%s\">%s</a>&gt;, %s<br>\r\n<b>%s</b>, <em>%s</em>",
		fake.Name(),
		*from,
		*from,
		fake.JobTitle(),
		company,
		fake.CompanyCatchPhrase())
	htmlp := append(make([]string, 0), paragraphs...)
	htmlp = append(htmlp, cosig)

	if *signature != "" {
		htmlp = append(htmlp, "<small>"+*signature+"</small>")
	}
*/
	textp := "The Free mail zone=0A=0ANeed an email to use on non-trusted websites? Free mail zone is the solution.=0A * All email address already exists, with the auto generated inbox feature. No registration needed. =0A   * Get your emails instantly in your new temporary email inbox. No page reload needed. =0A   * Access your email anywhere, anytime by using the direct link to your inbox. Don't forget to save it: http://myemail.freemailzone.com  =0A        * Your emails are automatically trashed  24 hours after reception. Automatic disposable email. =0A * Inboxes are not password protected. Hence, choose an unique non trivial inbox name. =0A=0AStart using the Free mail zone by pressing Generate random button or by following the link freemailzone.com (http://freemailzone.com)."
	htmlp:=`<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body><div data-html-editor-font-wrapper="true" style="font-family: arial, sans-serif; font-size: 13px;"><div><div><div style="font-family: arial, sans-serif;font-size: 13px"><div><div><div style="font-family: arial, sans-serif;font-size: 13px"> <br><span style="font-size: 16px"><strong>The Free mail zone</strong></span><br><br>Need an email to use on non-trusted websites? Free mail zone is the solution.<ul> <li>All email address already exists, with the auto generated inbox feature. <strong>No registration</strong> needed.</li> <li>Get your emails instantly in your new temporary email inbox. <strong>No page reload</strong> needed.</li> <li>Access your email anywhere, anytime by using the <strong>direct link</strong> to your inbox. Don't forget to save it: <strong>http://<span style="color: #2980b9"><em>myemail</em></span>.freemailzone.com</strong> </li> <li>Your emails are automatically trashed  24 hours after reception. <strong>Automatic disposable email</strong>.</li> <li>Mail boxes are limited to <strong>10 mails maximum</strong>.</li> <li>Inboxes are <strong>not password protected</strong>. Hence, choose an unique non trivial inbox name.</li> </ul>Start using the <span style="color: #2980b9"><strong>Free mail zone</strong></span> by pressing <span style="color: #2980b9"><strong>Generate random</strong></span> button or by following the link <a rel="external nofollow noopener noreferrer" target="_blank" tabindex="-1" href="http://freemailzone.com">freemailzone.com</a>.</div></div></div></div></div></div></div></body></html></p><p>`

	log.Println(*from, "->", *to,":",*subject)

	return enmime.Builder().
		From("", *from).
		To("", *to).
		Subject(*subject).
		Text([]byte(textp)).
		HTML([]byte(htmlp))
}
//		Text([]byte(strings.Join(textp, "\r\n\r\n"))).
//		HTML([]byte("<p>" + strings.Join(htmlp, "</p>\r\n<p>") + "</p>"))
